classdef NavierStokes < PDE
  methods % constructor
    function obj = NavierStokes(data, fesV, fesP)
      opList = {OpGradGrad(data.nu, fesV), ...
                OpGradId(@(x,t,U)U{1}, fesV, fesV), ...
                OpDivId(1, fesV, fesP), ...
                FcId(data.f, fesV, 0), ...
                OpIntId(fesP)};
      lhs.sys = {{1,2} {3} {}; ...
                   {3} {} {5}; ...
                   {} {5} {}};
      lhs.coeff = {{} {-1.0} {}; ...
                   {} {} {-1.0}; ...
                       {} {} {}};
      lhs.adj = {{} {1} {}; ...
                 {} {} {1}; ...
                 {} {} {}};
      rhs.sys = {{4}; {}; {}};
      %
      obj = obj@PDE(opList, lhs, rhs);
    end
  end
end
